version: '3'

services:
  docker-mysql:
    container_name: restaurant-database
    image: mysql:5.7
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=restaurant
      - MYSQL_PASSWORD=12345

  spring-boot-jpa-docker-webapp:
    image: goodfooddelivery/restaurant
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3366/Restaurant?createDatabaseIfNotExist=true