version: '3'

services:
  docker-mysql:
    image: mysql:8.0.11
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=restaurant
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345

  spring-boot-jpa-docker-webapp:
    image: docker.io/library/spring-boot:0.0.1-SNAPSHOT
    depends_on:
      - docker-mysql
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=restaurant
      - DATABASE_PORT=3366